# Generated by Django 4.2.19 on 2025-04-04 12:27

import allauth.idp.protocols.openid_connect.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=allauth.idp.protocols.openid_connect.models.default_client_id,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "secret",
                    models.CharField(
                        default=allauth.idp.protocols.openid_connect.models.default_client_secret,
                        max_length=200,
                    ),
                ),
                (
                    "scopes",
                    models.TextField(
                        help_text="The scope the client is allowed to request."
                    ),
                ),
                (
                    "grant_types",
                    models.TextField(
                        default="authorization_code",
                        help_text="A list of allowed grant types.",
                    ),
                ),
                ("redirect_uris", models.TextField()),
                (
                    "response_types",
                    models.TextField(
                        default="code", help_text="A list of allowed response types."
                    ),
                ),
                (
                    "skip_consent",
                    models.BooleanField(
                        default=False,
                        help_text="Flag to allow skip the consent screen for this client",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("data", models.JSONField(blank=True, default=None, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("at", "Access token"),
                            ("rt", "Refresh token"),
                            ("ac", "Authorization code"),
                        ],
                        max_length=2,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "value",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("scopes", models.TextField(default="")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="allauth_idp_oidc.client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
